### ISSUE TITLE
The game "Kirby:Whispy" (MIO-ID: G-mgkn-88-0) does not play correctly

### ISSUE THREAD

**Issue by windwakr** [yeahross0/Mio-Micro#1]
This game does not work correctly in the web player on DoujinSoft. It's supposed to be a boss fight against Whispy Woods and works properly when injected into a real copy of the game. In the web player none of the mechanics work at all.

**Comment by yeahross0** [comment]
I'll look into it. Made some fixes:

![firefox_tksJKO0fvY](https://github.com/yeahross0/Mio-Micro/assets/62470996/93edcae3-76ab-4f47-96fb-1826464ef934)

**Comment by yeahross0** [comment]
I've updated the itch.io page. Notified Doujinsoft of available upgrade.
